/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTvRouteImport } from './routes/_authenticated/tv'
import { Route as AuthenticatedDowntimeRouteImport } from './routes/_authenticated/downtime'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedStationStationIdRouteImport } from './routes/_authenticated/station.$stationId'
import { Route as AuthenticatedLineLineIdRouteImport } from './routes/_authenticated/line.$lineId'
import { Route as AuthenticatedAdminWorkOrdersRouteImport } from './routes/_authenticated/admin.work-orders'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminStructureRouteImport } from './routes/_authenticated/admin.structure'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminEdgeNodesRouteImport } from './routes/_authenticated/admin.edge-nodes'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTvRoute = AuthenticatedTvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDowntimeRoute = AuthenticatedDowntimeRouteImport.update({
  id: '/downtime',
  path: '/downtime',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStationStationIdRoute =
  AuthenticatedStationStationIdRouteImport.update({
    id: '/station/$stationId',
    path: '/station/$stationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLineLineIdRoute = AuthenticatedLineLineIdRouteImport.update({
  id: '/line/$lineId',
  path: '/line/$lineId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminWorkOrdersRoute =
  AuthenticatedAdminWorkOrdersRouteImport.update({
    id: '/admin/work-orders',
    path: '/admin/work-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminStructureRoute =
  AuthenticatedAdminStructureRouteImport.update({
    id: '/admin/structure',
    path: '/admin/structure',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/admin/products',
    path: '/admin/products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEdgeNodesRoute =
  AuthenticatedAdminEdgeNodesRouteImport.update({
    id: '/admin/edge-nodes',
    path: '/admin/edge-nodes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/downtime': typeof AuthenticatedDowntimeRoute
  '/tv': typeof AuthenticatedTvRoute
  '/admin/edge-nodes': typeof AuthenticatedAdminEdgeNodesRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/structure': typeof AuthenticatedAdminStructureRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/work-orders': typeof AuthenticatedAdminWorkOrdersRoute
  '/line/$lineId': typeof AuthenticatedLineLineIdRoute
  '/station/$stationId': typeof AuthenticatedStationStationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/downtime': typeof AuthenticatedDowntimeRoute
  '/tv': typeof AuthenticatedTvRoute
  '/admin/edge-nodes': typeof AuthenticatedAdminEdgeNodesRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/structure': typeof AuthenticatedAdminStructureRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/work-orders': typeof AuthenticatedAdminWorkOrdersRoute
  '/line/$lineId': typeof AuthenticatedLineLineIdRoute
  '/station/$stationId': typeof AuthenticatedStationStationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/downtime': typeof AuthenticatedDowntimeRoute
  '/_authenticated/tv': typeof AuthenticatedTvRoute
  '/_authenticated/admin/edge-nodes': typeof AuthenticatedAdminEdgeNodesRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/structure': typeof AuthenticatedAdminStructureRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/work-orders': typeof AuthenticatedAdminWorkOrdersRoute
  '/_authenticated/line/$lineId': typeof AuthenticatedLineLineIdRoute
  '/_authenticated/station/$stationId': typeof AuthenticatedStationStationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/alerts'
    | '/dashboard'
    | '/downtime'
    | '/tv'
    | '/admin/edge-nodes'
    | '/admin/products'
    | '/admin/structure'
    | '/admin/users'
    | '/admin/work-orders'
    | '/line/$lineId'
    | '/station/$stationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/alerts'
    | '/dashboard'
    | '/downtime'
    | '/tv'
    | '/admin/edge-nodes'
    | '/admin/products'
    | '/admin/structure'
    | '/admin/users'
    | '/admin/work-orders'
    | '/line/$lineId'
    | '/station/$stationId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/alerts'
    | '/_authenticated/dashboard'
    | '/_authenticated/downtime'
    | '/_authenticated/tv'
    | '/_authenticated/admin/edge-nodes'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/structure'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/work-orders'
    | '/_authenticated/line/$lineId'
    | '/_authenticated/station/$stationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tv': {
      id: '/_authenticated/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof AuthenticatedTvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/downtime': {
      id: '/_authenticated/downtime'
      path: '/downtime'
      fullPath: '/downtime'
      preLoaderRoute: typeof AuthenticatedDowntimeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/station/$stationId': {
      id: '/_authenticated/station/$stationId'
      path: '/station/$stationId'
      fullPath: '/station/$stationId'
      preLoaderRoute: typeof AuthenticatedStationStationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/line/$lineId': {
      id: '/_authenticated/line/$lineId'
      path: '/line/$lineId'
      fullPath: '/line/$lineId'
      preLoaderRoute: typeof AuthenticatedLineLineIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/work-orders': {
      id: '/_authenticated/admin/work-orders'
      path: '/admin/work-orders'
      fullPath: '/admin/work-orders'
      preLoaderRoute: typeof AuthenticatedAdminWorkOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/structure': {
      id: '/_authenticated/admin/structure'
      path: '/admin/structure'
      fullPath: '/admin/structure'
      preLoaderRoute: typeof AuthenticatedAdminStructureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/edge-nodes': {
      id: '/_authenticated/admin/edge-nodes'
      path: '/admin/edge-nodes'
      fullPath: '/admin/edge-nodes'
      preLoaderRoute: typeof AuthenticatedAdminEdgeNodesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDowntimeRoute: typeof AuthenticatedDowntimeRoute
  AuthenticatedTvRoute: typeof AuthenticatedTvRoute
  AuthenticatedAdminEdgeNodesRoute: typeof AuthenticatedAdminEdgeNodesRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminStructureRoute: typeof AuthenticatedAdminStructureRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWorkOrdersRoute: typeof AuthenticatedAdminWorkOrdersRoute
  AuthenticatedLineLineIdRoute: typeof AuthenticatedLineLineIdRoute
  AuthenticatedStationStationIdRoute: typeof AuthenticatedStationStationIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDowntimeRoute: AuthenticatedDowntimeRoute,
  AuthenticatedTvRoute: AuthenticatedTvRoute,
  AuthenticatedAdminEdgeNodesRoute: AuthenticatedAdminEdgeNodesRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminStructureRoute: AuthenticatedAdminStructureRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWorkOrdersRoute: AuthenticatedAdminWorkOrdersRoute,
  AuthenticatedLineLineIdRoute: AuthenticatedLineLineIdRoute,
  AuthenticatedStationStationIdRoute: AuthenticatedStationStationIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
